# Stage 1: Build Stage
FROM node:18-alpine AS build

WORKDIR /app

# Accept build arguments
ARG VITE_REACT_APP_API_URL
ARG VITE_REACT_APP_ENV_TYPE

# Define env vars
ENV VITE_REACT_APP_API_URL=$VITE_REACT_APP_API_URL
ENV VITE_REACT_APP_ENV_TYPE=$VITE_REACT_APP_ENV_TYPE

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Build the app (dist folder will be created)
RUN npm run build

# Final image is not needed — output is used by nginx container through volume
FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf