version: "3.8"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 5s

  backend:
    container_name: backend_container
    build: ./backend
    ports: 
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017/passop
    depends_on:
      - mongo_db



  frontend:
    container_name: frontend_container
    build: ./frontend
    ports: 
      - 5173:5173
    environment:
      VITE_REACT_APP_API_URL: http://localhost:3000
    depends_on:
      - backend


volumes:
  mongo_db: 

    
      