version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes: 
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 5s

  backend:
    container_name: backend
    build: ./backend
    environment:
      MONGO_URI: mongodb://mongo:27017/passop
    depends_on:
      - mongo
    expose:
      - "3000"

  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: dockerfile
      environment:
        VITE_REACT_APP_API_URL: http://backend:3000
      volumes:
      - frontend-build:/shared
      depends_on:
      - backend
      ports:
      - "80:80"


volumes:
  mongo-data: 
  frontend-build:

networks:
  default:
    name: passwordmanager-net


    
      