FROM node:21 AS backend-builder

WORKDIR /app

COPY . .

RUN npm install

#  stage 2

FROM node:21-slim

WORKDIR /app

COPY --from=backend-builder /app .

COPY . .

EXPOSE 3000

CMD ["node", "server.js"]
